//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class costosHojaRuta
    {
        public int idCosto { get; set; }
        public int idHojaRuta { get; set; }
        public string concepto { get; set; }
        public int numDocumento { get; set; }
        public string proveedor { get; set; }
        public int monto { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual hojaRuta hojaRuta { get; set; }
    }
}
