//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hojaRutaDetalle
    {
        public int idHojaRutaDetalle { get; set; }
        public int idHojaRuta { get; set; }
        public Nullable<System.DateTime> fechaSalida { get; set; }
        public Nullable<System.DateTime> fechaLlegada { get; set; }
        public string observaciones { get; set; }
    
        public virtual hojaRuta hojaRuta { get; set; }
    }
}
